import Foundation
import CoreData
import PDFKit
import UniformTypeIdentifiers

// 用于JSON导出的数据结构
struct ProductExportData: Codable {
    var name: String
    var brand: String
    var model: String
    var notes: String
    var categoryName: String?
    var order: OrderExportData?
}

struct OrderExportData: Codable {
    var orderNumber: String?
    var platform: String?
    var orderDate: String
    var warrantyPeriod: Int?
}

class ExportService {
    // 导出为CSV格式
    static func exportToCSV(products: [Product]) -> Data? {
        let header = ["名称", "品牌", "型号", "分类", "购买日期", "购买平台", "订单号", "保修状态", "保修期(月)", "备注"]
        var rows: [[String]] = []
        
        for product in products {
            // 计算保修期月数
            var warrantyMonths = ""
            if let order = product.order,
               let orderDate = order.orderDate,
               let warrantyEndDate = order.warrantyEndDate {
                let months = Calendar.current.dateComponents([.month], from: orderDate, to: warrantyEndDate).month ?? 0
                warrantyMonths = "\(months)"
            }
            
            let row = [
                product.productName,
                product.productBrand,
                product.productModel,
                product.category?.categoryName ?? "",
                product.order?.displayDate.formatted() ?? "",
                product.order?.displayPlatform ?? "",
                product.order?.displayOrderNumber ?? "",
                product.order?.warrantyStatus.description ?? "",
                warrantyMonths,
                product.productNotes
            ]
            rows.append(row)
        }
        
        // 将所有字段用双引号包裹，处理字段中的双引号
        let processedRows = rows.map { row in
            row.map { field in
                "\"\(field.replacingOccurrences(of: "\"", with: "\"\""))\""
            }.joined(separator: ",")
        }
        
        let csvString = ([header.joined(separator: ",")] + processedRows).joined(separator: "\n")
        return csvString.data(using: .utf8)
    }
    
    // 导出为JSON格式
    static func exportToJSON(products: [Product]) -> Data? {
        var exportData: [ProductExportData] = []
        
        for product in products {
            var productData = ProductExportData(
                name: product.productName,
                brand: product.productBrand,
                model: product.productModel,
                notes: product.productNotes,
                categoryName: product.category?.categoryName
            )
            
            // 添加订单信息
            if let order = product.order,
               let orderDate = order.orderDate {
                let formatter = ISO8601DateFormatter()
                
                // 计算保修期月数
                var warrantyMonths: Int?
                if let warrantyEndDate = order.warrantyEndDate {
                    warrantyMonths = Calendar.current.dateComponents([.month], from: orderDate, to: warrantyEndDate).month
                }
                
                productData.order = OrderExportData(
                    orderNumber: order.orderNumber,
                    platform: order.platform,
                    orderDate: formatter.string(from: orderDate),
                    warrantyPeriod: warrantyMonths
                )
            }
            
            exportData.append(productData)
        }
        
        // 编码为JSON
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        
        do {
            return try encoder.encode(exportData)
        } catch {
            print("JSON编码失败: \(error.localizedDescription)")
            return nil
        }
    }
    
    // 导出为PDF格式
    @MainActor
    static func exportToPDF(products: [Product]) -> Data? {
        let pdfMetaData: [String: Any] = [
            kCGPDFContextCreator as String: "ManualBox",
            kCGPDFContextAuthor as String: "Generated by ManualBox",
            kCGPDFContextTitle as String: "商品记录导出"
        ]
        
        let pageWidth: CGFloat = 595.2 // A4
        let pageHeight: CGFloat = 841.8 // A4
        var mediaBox = CGRect(x: 0, y: 0, width: pageWidth, height: pageHeight)
        
        #if os(macOS)
        let data = NSMutableData()
        guard let consumer = CGDataConsumer(data: data as CFMutableData),
              let context = CGContext(consumer: consumer,
                                    mediaBox: &mediaBox,
                                    pdfMetaData as CFDictionary) else {
            return nil
        }
        
        for (index, product) in products.enumerated() {
            if index > 0 {
                context.beginPage(mediaBox: &mediaBox)
            }
            
            // 绘制商品信息
            let attributes = [
                NSAttributedString.Key.font: NSFont.systemFont(ofSize: 12)
            ]
            
            var y: CGFloat = pageHeight - 50
            let leftMargin: CGFloat = 50
            
            // 标题
            let titleAttributes = [
                NSAttributedString.Key.font: NSFont.boldSystemFont(ofSize: 16)
            ]
            NSAttributedString(string: product.productName,
                             attributes: titleAttributes).draw(at: NSPoint(x: leftMargin, y: y))
            y -= 30
            
            // 基本信息
            let info = [
                "品牌": product.productBrand,
                "型号": product.productModel,
                "分类": product.category?.categoryName ?? "",
                "购买日期": product.order?.displayDate.formatted() ?? "",
                "购买平台": product.order?.displayPlatform ?? "",
                "订单号": product.order?.displayOrderNumber ?? "",
                "保修状态": product.order?.warrantyStatus.description ?? ""
            ]
            
            for (key, value) in info {
                let text = "\(key): \(value)"
                NSAttributedString(string: text,
                                 attributes: attributes).draw(at: NSPoint(x: leftMargin, y: y))
                y -= 20
            }
            
            // 如果有图片，绘制图片
            if let imageData = product.imageData,
               let image = PlatformImage(data: imageData) {
                let maxWidth: CGFloat = 200
                let maxHeight: CGFloat = 200
                let aspectRatio = image.size.width / image.size.height
                
                var drawWidth = maxWidth
                var drawHeight = maxWidth / aspectRatio
                
                if drawHeight > maxHeight {
                    drawHeight = maxHeight
                    drawWidth = maxHeight * aspectRatio
                }
                
                if let cgImage = image.cgImage(forProposedRect: nil, context: nil, hints: nil) {
                    context.draw(cgImage, in: CGRect(
                        x: leftMargin,
                        y: y - drawHeight,
                        width: drawWidth,
                        height: drawHeight
                    ))
                }
            }
        }
        
        context.closePDF()
        return data as Data
        
        #else
        let format = UIGraphicsPDFRendererFormat()
        format.documentInfo = pdfMetaData
        
        let renderer = UIGraphicsPDFRenderer(
            bounds: CGRect(x: 0, y: 0, width: pageWidth, height: pageHeight),
            format: format
        )
        
        return renderer.pdfData { context in
            for (index, product) in products.enumerated() {
                context.beginPage()
                
                // 绘制商品信息
                let attributes = [
                    NSAttributedString.Key.font: UIFont.systemFont(ofSize: 12)
                ]
                
                var y: CGFloat = pageHeight - 50
                let leftMargin: CGFloat = 50
                
                // 标题
                let titleAttributes = [
                    NSAttributedString.Key.font: UIFont.boldSystemFont(ofSize: 16)
                ]
                NSString(string: product.productName).draw(
                    at: CGPoint(x: leftMargin, y: y),
                    withAttributes: titleAttributes
                )
                y -= 30
                
                // 基本信息
                let info = [
                    "品牌": product.productBrand,
                    "型号": product.productModel,
                    "分类": product.category?.categoryName ?? "",
                    "购买日期": product.order?.displayDate.formatted() ?? "",
                    "购买平台": product.order?.displayPlatform ?? "",
                    "订单号": product.order?.displayOrderNumber ?? "",
                    "保修状态": product.order?.warrantyStatus.description ?? ""
                ]
                
                for (key, value) in info {
                    let text = "\(key): \(value)"
                    NSString(string: text).draw(
                        at: CGPoint(x: leftMargin, y: y),
                        withAttributes: attributes
                    )
                    y -= 20
                }
                
                // 如果有图片，绘制图片
                if let imageData = product.imageData,
                   let image = PlatformImage(data: imageData) {
                    let maxWidth: CGFloat = 200
                    let maxHeight: CGFloat = 200
                    let aspectRatio = image.size.width / image.size.height
                    
                    var drawWidth = maxWidth
                    var drawHeight = maxWidth / aspectRatio
                    
                    if drawHeight > maxHeight {
                        drawHeight = maxHeight
                        drawWidth = maxHeight * aspectRatio
                    }
                    
                    image.draw(in: CGRect(
                        x: leftMargin,
                        y: y - drawHeight,
                        width: drawWidth,
                        height: drawHeight
                    ))
                }
            }
        }
        #endif
    }
    
    // 保存文件到磁盘
    static func saveFile(_ data: Data, name: String, ext: String) -> URL? {
        let tempDir = FileManager.default.temporaryDirectory
        let fileURL = tempDir.appendingPathComponent(name).appendingPathExtension(ext)
        
        do {
            try data.write(to: fileURL)
            return fileURL
        } catch {
            print("保存文件失败: \(error.localizedDescription)")
            return nil
        }
    }
}