import Foundation
import CoreData
import PDFKit
import UniformTypeIdentifiers
#if os(iOS)
import UIKit
#elseif os(macOS)
import AppKit
#endif

// MARK: - ExportService
class ExportService {
    // 导出为CSV格式
    static func exportToCSV(products: [Product]) -> Data? {
        let header = ["名称", "品牌", "型号", "分类", "购买日期", "购买平台", "订单号", "保修状态", "保修期(月)", "备注"]
        var rows: [[String]] = []
        
        for product in products {
            // 计算保修期月数
            var warrantyMonths = ""
            if let order = product.order,
               let orderDate = order.orderDate,
               let warrantyEndDate = order.warrantyEndDate {
                let months = Calendar.current.dateComponents([.month], from: orderDate, to: warrantyEndDate).month ?? 0
                warrantyMonths = "\(months)"
            }
            
            let row = [
                product.productName,
                product.productBrand,
                product.productModel,
                product.category?.categoryName ?? "",
                product.order?.displayDate.formatted() ?? "",
                product.order?.displayPlatform ?? "",
                product.order?.displayOrderNumber ?? "",
                product.hasActiveWarranty ? "保修中" : "已过保",
                warrantyMonths,
                product.productNotes
            ]
            rows.append(row)
        }
        
        // 将所有字段用双引号包裹，处理字段中的双引号
        let processedRows = rows.map { row in
            row.map { field in
                "\"\(field.replacingOccurrences(of: "\"", with: "\"\""))\""
            }.joined(separator: ",")
        }
        
        let csvString = ([header.joined(separator: ",")] + processedRows).joined(separator: "\n")
        return csvString.data(using: .utf8)
    }
    
    // 导出为JSON格式
    static func exportToJSON(products: [Product]) -> Data? {
        let exportData = products.map { ProductExportData(from: $0) }
        
        // 编码为JSON
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        encoder.dateEncodingStrategy = .iso8601
        
        do {
            return try encoder.encode(exportData)
        } catch {
            print("JSON编码失败: \(error.localizedDescription)")
            return nil
        }
    }
    
    // 导出为PDF格式
    @MainActor
    static func exportToPDF(products: [Product]) -> Data? {
        let pdfMetaData: [String: Any] = [
            kCGPDFContextCreator as String: "ManualBox",
            kCGPDFContextAuthor as String: "Generated by ManualBox",
            kCGPDFContextTitle as String: "商品记录导出"
        ]
        
        let pageWidth: CGFloat = 595.2 // A4
        let pageHeight: CGFloat = 841.8 // A4
        var mediaBox = CGRect(x: 0, y: 0, width: pageWidth, height: pageHeight)
        
        #if os(macOS)
        let data = NSMutableData()
        guard let consumer = CGDataConsumer(data: data as CFMutableData),
              let context = CGContext(consumer: consumer,
                                    mediaBox: &mediaBox,
                                    pdfMetaData as CFDictionary) else {
            return nil
        }
        
        context.beginPDFPage(nil)
        
        // 绘制商品信息
        let attributes = [
            NSAttributedString.Key.font: NSFont.systemFont(ofSize: 12)
        ]
        
        var y: CGFloat = pageHeight - 50
        let leftMargin: CGFloat = 50
        
        // 标题
        let titleAttributes = [
            NSAttributedString.Key.font: NSFont.boldSystemFont(ofSize: 16)
        ]
        
        for (index, product) in products.enumerated() {
            if index > 0 && y < 100 {
                context.endPDFPage()
                context.beginPDFPage(nil)
                y = pageHeight - 50
            }
            
            NSAttributedString(string: product.productName,
                             attributes: titleAttributes).draw(at: NSPoint(x: leftMargin, y: y))
            y -= 30
            
            // 基本信息
            let info = [
                "品牌": product.productBrand,
                "型号": product.productModel,
                "分类": product.category?.categoryName ?? "",
                "购买日期": product.order?.displayDate.formatted() ?? "",
                "购买平台": product.order?.displayPlatform ?? "",
                "订单号": product.order?.displayOrderNumber ?? "",
                "保修状态": product.hasActiveWarranty ? "保修中" : "已过保"
            ]
            
            for (key, value) in info {
                let text = "\(key): \(value)"
                NSAttributedString(string: text,
                                 attributes: attributes).draw(at: NSPoint(x: leftMargin, y: y))
                y -= 20
            }
            
            y -= 20 // 产品间距
        }
        
        context.endPDFPage()
        context.closePDF()
        return data as Data
        
        #else
        let format = UIGraphicsPDFRendererFormat()
        format.documentInfo = pdfMetaData
        
        let renderer = UIGraphicsPDFRenderer(
            bounds: CGRect(x: 0, y: 0, width: pageWidth, height: pageHeight),
            format: format
        )
        
        return renderer.pdfData { context in
            context.beginPage()
            
            // 绘制商品信息
            let attributes = [
                NSAttributedString.Key.font: UIFont.systemFont(ofSize: 12)
            ]
            
            var y: CGFloat = pageHeight - 50
            let leftMargin: CGFloat = 50
            
            // 标题
            let titleAttributes = [
                NSAttributedString.Key.font: UIFont.boldSystemFont(ofSize: 16)
            ]
            
            for (index, product) in products.enumerated() {
                if index > 0 && y < 100 {
                    context.beginPage()
                    y = pageHeight - 50
                }
                
                NSString(string: product.productName).draw(
                    at: CGPoint(x: leftMargin, y: y),
                    withAttributes: titleAttributes
                )
                y -= 30
                
                // 基本信息
                let info = [
                    "品牌": product.productBrand,
                    "型号": product.productModel,
                    "分类": product.category?.categoryName ?? "",
                    "购买日期": product.order?.displayDate.formatted() ?? "",
                    "购买平台": product.order?.displayPlatform ?? "",
                    "订单号": product.order?.displayOrderNumber ?? "",
                    "保修状态": product.hasActiveWarranty ? "保修中" : "已过保"
                ]
                
                for (key, value) in info {
                    let text = "\(key): \(value)"
                    NSString(string: text).draw(
                        at: CGPoint(x: leftMargin, y: y),
                        withAttributes: attributes
                    )
                    y -= 20
                }
                
                y -= 20 // 产品间距
            }
        }
        #endif
    }
    
    // 保存文件到磁盘
    static func saveFile(_ data: Data, name: String, ext: String) -> URL? {
        let tempDir = FileManager.default.temporaryDirectory
        let fileURL = tempDir.appendingPathComponent(name).appendingPathExtension(ext)
        
        do {
            try data.write(to: fileURL)
            return fileURL
        } catch {
            print("保存文件失败: \(error.localizedDescription)")
            return nil
        }
    }
}

// MARK: - Supporting Types
struct ProductExportData: Codable {
    let name: String
    let brand: String?
    let model: String?
    let notes: String?
    let categoryName: String?
    let orderDate: String?
    let orderNumber: String?
    let platform: String?
    let warrantyStatus: String?
    let warrantyPeriod: Int?
    
    init(from product: Product) {
        self.name = product.productName
        self.brand = product.productBrand
        self.model = product.productModel
        self.notes = product.productNotes
        self.categoryName = product.category?.categoryName
        
        if let order = product.order {
            let formatter = ISO8601DateFormatter()
            self.orderDate = order.orderDate != nil ? formatter.string(from: order.orderDate!) : nil
            self.orderNumber = order.displayOrderNumber
            self.platform = order.displayPlatform
            
            if let orderDate = order.orderDate, let warrantyEndDate = order.warrantyEndDate {
                self.warrantyStatus = product.hasActiveWarranty ? "保修中" : "已过保"
                self.warrantyPeriod = Calendar.current.dateComponents([.month], from: orderDate, to: warrantyEndDate).month
            } else {
                self.warrantyStatus = nil
                self.warrantyPeriod = nil
            }
        } else {
            self.orderDate = nil
            self.orderNumber = nil
            self.platform = nil
            self.warrantyStatus = nil
            self.warrantyPeriod = nil
        }
    }
}